-- ─────────────────────────────────────────────────────────────
-- 0008_social_webhook.sql
-- Outbound "share on publish" webhook — the no-OAuth path to auto-share.
--
-- Native OAuth posting (0007) requires each platform's app review, which can
-- take weeks. A webhook lets an owner pipe every published post into Zapier /
-- Make / n8n (→ any network) and turn on auto-share *today*. The cron POSTs a
-- JSON payload (canonical URL + per-platform copy + cover image) signed with
-- an HMAC-SHA256 secret so the receiver can verify it came from Grove.
-- ─────────────────────────────────────────────────────────────

alter table public.domains
  add column if not exists social_webhook_url    text,
  -- per-domain signing secret; generated by the app when the URL is first set.
  add column if not exists social_webhook_secret text;
